server:
    port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG

spring:
  application:
    name: apigateway
  cloud:
    gateway:
      routes:
      - id: role_service
        uri: lb://role-service
        predicates:
        #- Path=/api/v1/role/**
        - Path=/**

